# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 117d97d170efd075c2110d1f8e2f8ee6005a3b00cfaefc6044ff60dc4ba5ccddeda20e308efdd6fb7f241f2d1c1a8079fbaa6e17bc11511c8b79136765e67fec

test:
  secret_key_base: 2fa42fcf69f97332f50b81f88f97ca561d1abeefe84811ab5039775869bb5fd08eabfa5249ee14fc2d2dd0e20b0fcfca3b52fcf53419fbf8fd34c2345944e02f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
